### PR TITLE
fix: Fixed spelling of 'ChaosCenter' in Sidebar Concepts section

### PR DESCRIPTION
**Pull request by hajowieland**
Signed-off-by: hajowieland <mail@wieland.tech>

**What this PR does / why we need it**:

Just a small spelling fix in the Concept section of the sidebar in our documentation.

**Special notes for your reviewer**:

--

### CODE REVIEW

**Comment by hajowieland** [comment]
bump

**Review by gdsoumya — APPROVED** [review]

**Comment by gdsoumya** [comment]
@hajowieland apologies for the delay, this pr went unnoticed. Will get it merged asap.

**Comment by gdsoumya** [comment]
Also realized that there are other places too in the docs where the same error is present would you like to maybe do a global search and replace in the repo and fix all of them in this PR @hajowieland

**Comment by hajowieland** [comment]
@gdsoumya no worries - I replaced all occurrences of misspelled `ChoasCenter` with a global search and replace.

**Comment by gdsoumya** [comment]
@hajowieland awesome thanks, will merge once ci completes

**Pull request merged**
